// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScientificStudiesRecord.Data;

namespace ScientificStudiesRecord.Migrations
{
    [DbContext(typeof(ScientificStudiesRecordDbContext))]
    [Migration("20190821165250_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ScientificStudiesRecord.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(256);

                    b.Property<long>("Duration");

                    b.Property<int>("TaskId");

                    b.Property<int>("TestSubjectId");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TestSubjectId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.StudyGroup", b =>
                {
                    b.Property<int>("StudyId");

                    b.Property<int>("GroupId");

                    b.HasKey("StudyId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("StudyGroup");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.StudyTestSubject", b =>
                {
                    b.Property<int>("StudyId");

                    b.Property<int>("TestSubjectId");

                    b.HasKey("StudyId", "TestSubjectId");

                    b.HasIndex("TestSubjectId");

                    b.ToTable("StudyTestSubject");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("StudyId");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.TestSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(256);

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TestSubjects");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PaswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.Experiment", b =>
                {
                    b.HasOne("ScientificStudiesRecord.Models.Task", "Task")
                        .WithMany("Experiments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificStudiesRecord.Models.TestSubject", "TestSubject")
                        .WithMany("Experiments")
                        .HasForeignKey("TestSubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.StudyGroup", b =>
                {
                    b.HasOne("ScientificStudiesRecord.Models.Group", "Group")
                        .WithMany("StudyGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificStudiesRecord.Models.Study", "Study")
                        .WithMany("StudyGroups")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.StudyTestSubject", b =>
                {
                    b.HasOne("ScientificStudiesRecord.Models.Study", "Study")
                        .WithMany("StudyTestSubjects")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificStudiesRecord.Models.TestSubject", "TestSubject")
                        .WithMany("StudyTestSubjects")
                        .HasForeignKey("TestSubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificStudiesRecord.Models.Task", b =>
                {
                    b.HasOne("ScientificStudiesRecord.Models.Study", "Study")
                        .WithMany("Tasks")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
